"""New migration

Revision ID: eca9ac729aa9
Revises: f6b827eaee4b
Create Date: 2025-12-15 22:15:52.611205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eca9ac729aa9'
down_revision: Union[str, Sequence[str], None] = 'f6b827eaee4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_details',
    sa.Column('fullname', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('username')
    )
    op.create_table('add_query',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_username', sa.String(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('concern', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('answer_summary', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_username'], ['user_details.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('add_query')
    op.drop_table('user_details')
    # ### end Alembic commands ###
