"""empty message

Revision ID: f6b827eaee4b
Revises: 
Create Date: 2025-12-15 15:45:32.627273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6b827eaee4b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_details', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('user_details', sa.Column('fullname', sa.String(), nullable=False))
    op.add_column('user_details', sa.Column('email', sa.String(), nullable=True))
    op.add_column('user_details', sa.Column('username', sa.String(), nullable=False))
    op.add_column('user_details', sa.Column('password', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'user_details', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_details', type_='unique')
    op.drop_column('user_details', 'password')
    op.drop_column('user_details', 'username')
    op.drop_column('user_details', 'email')
    op.drop_column('user_details', 'fullname')
    op.drop_column('user_details', 'id')
    # ### end Alembic commands ###
